# Generated by Django 5.0.3 on 2024-03-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(default="", null=True),
        ),
    ]
