# Generated by Django 5.0.3 on 2024-03-07 03:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
